name: appikorn_madix_widgets
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-128.0.dev <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  data_table_2: ^2.5.7
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.19.0
#  webviewx: ^0.2.2
  json_editor: ^0.0.8
  flutter_cache_manager: any
  http: any
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  crypto: any
  two_dimensional_scrollables: ^0.3.1
  jiffy: ^6.3.1
  lottie: ^3.3.1

  mix: ^1.5.2


dependency_overrides:
  intl: ^0.18.0
  jiffy: ^6.3.1
  http: ^0.13.3
#  webview_flutter: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/animation/
